# Generated by Django 3.2.24 on 2024-03-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240318_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateField(auto_now_add=True)),
                ('sponsorType', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UniversityName', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('study_field', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='scholarship_logo/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='workbook',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='course_img/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizQuestions',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='WorkBook',
        ),
    ]
